Authentication improvements, AuthProvider
elixir-webrtc/rel pull request #4
Opened 2023-07-13 13:30 UTC by LVala

2023-07-14 20:47 UTC, mickel8 requested changes
Really nice and clean code!

I added a couple of minor suggestions with 2 or 3 blockers but easy to fix

2023-07-14 20:47 UTC, mickel8 commented on lib/ex_turn/auth_provider.ex
> +         true <- key == Application.fetch_env!(:ex_turn, :auth_provider_key) do
We want this service to be publicly available so we don't need api key

2023-07-14 20:47 UTC, mickel8 commented on lib/ex_turn/auth.ex
> +  @spec authenticate(Message.t(), username: String.t()) :: {:ok, binary()} | {:error, Message.t()}
We always need username, don't we? Instead of using keyword list , let's pass it as a second argument

2023-07-14 20:47 UTC, mickel8 commented on lib/ex_turn/auth.ex
> +  @spec generate_credentials(String.t() | nil) :: {String.t(), String.t(), non_neg_integer()}
Sometimes, when returned types are generic, it's helpful to explicitly name what we return

```suggestion
  @spec generate_credentials(String.t() | nil) :: {username :: String.t(), password :: String.t(), ttl :: non_neg_integer()}
  ```
```

2023-07-14 20:47 UTC, mickel8 commented on lib/ex_turn/auth.ex
> +    if String.to_integer(expiry_time) - System.os_time(:second) <= 0 do
String.to_integer might fail so we probably want to use Integer.parse

2023-07-14 20:47 UTC, mickel8 commented on lib/ex_turn/auth.ex
> +  @credentials_lifetime 24 * 60 * 60
Let's make this configurable with 1 day as a default. In our deployment we want these credentials to expire faster, like after 1-2 hours

2023-07-14 20:47 UTC, mickel8 commented on lib/ex_turn/auth_provider.ex
> +      Logger.info("Generated credentials: #{inspect(username)}, #{inspect(password)}")
We should avoid logging confidential data. Either anonimize it or remove the log

2023-07-14 20:47 UTC, mickel8 commented on lib/ex_turn/auth_provider.ex
> +  defp ip_to_string(addr) when is_tuple(addr) do
Use https://www.erlang.org/doc/man/inet.html#ntoa-1

2023-07-17 08:27 UTC, LVala commented on lib/ex_turn/auth.ex
> +  @spec authenticate(Message.t(), username: String.t()) :: {:ok, binary()} | {:error, Message.t()}
Not really, [this RFC](https://datatracker.ietf.org/doc/html/draft-uberti-rtcweb-turn-rest-00#section-4.2) specifies that at first we only check the timestamp embedded in the `USERNAME` attribute and only later check if the `USERNAME` matches the one used in `allocate` request. Assuming that the REST service is the only form of authentication we provide, we don't have any username to check against the one in the `allocate` request anyways.

2023-07-17 08:40 UTC, LVala commented on lib/ex_turn/auth_provider.ex
> +  defp ip_to_string(addr) when is_tuple(addr) do
I literally searched in `:inet` for function like this, but names like `ntoa` doesn't make it easy.

2023-07-17 09:45 UTC, mickel8 commented on lib/ex_turn/auth_provider.ex
> +  defp ip_to_string(addr) when is_tuple(addr) do
Erlang API is not the most intuitive one :smile:

2023-07-17 09:48 UTC, mickel8 approved these changes

2023-07-17 09:48 UTC, mickel8 commented on lib/ex_turn/auth_provider.ex
> +        Logger.info("Rejected credential request from #{:inet.ntoa(conn.remote_ip)}")
Let's add the reason to this log i.e. "invalid request" and log the request so that we know what's going on

2023-07-17 10:01 UTC, merged